#!/bin/sh -e
exec >>/root/uci-defaults.log 2>&1
# UCI system settings

echo "================="
echo "Setting base UCI settings."
uci -q batch << EOI
set system.@system[0].zonename='Europe/Amsterdam'
set system.@system[0].hostname='router'
set system.@system[0].timezone='CET-1CEST,M3.5.0,M10.5.0/3'

set system.ntp=timeserver
set system.ntp.server='0.openwrt.pool.ntp.org' '1.openwrt.pool.ntp.org' '2.openwrt.pool.ntp.org' '3.openwrt.pool.ntp.org'
set system.ntp.enable_server='1'

commit system
EOI

echo '-- config after:'
uci show system
echo

