#!/bin/sh -e
exec >>/root/uci-defaults.log 2>&1

echo "================="
echo "Setting networking settings."

uci -q batch << EOI

set network.loopback=interface
set network.loopback.proto='static'
set network.loopback.ipaddr='127.0.0.1'
set network.loopback.netmask='255.0.0.0'
set network.loopback.device='lo'

set network.globals=globals
set network.globals.ula_prefix='fd4a:7359:2a66::/48'

set network.lan=interface
set network.lan.proto='static'
set network.lan.netmask='255.255.255.0'
set network.lan.ip6assign='60'
set network.lan.ipaddr='10.0.0.1'
set network.lan.device='br-lan'
add_list network.lan.dns='1.1.1.1' 
add_list network.lan.dns='1.0.0.1' 
add_list network.lan.dns='8.8.8.8'

set network.wan=interface
set network.wan.proto='dhcp'
set network.wan.delegate='0'
set network.wan.broadcast='1'
set network.wan.device='eth0.100'
set network.wan.peerdns='0'
add_list network.wan.dns='1.1.1.1' 
add_list network.wan.dns='1.0.0.1' 
add_list network.wan.dns='8.8.8.8'

set network.VPN=interface
set network.VPN.proto='none'
set network.VPN.device='tun0'

set network.@device[0]=device
set network.@device[0].name='br-lan'
set network.@device[0].type='bridge'
set network.@device[0].ports='eth1' 'eth2'


delete network.wan6

commit network

EOI


echo '-- config after:'
uci show network
echo
