#!/bin/sh -e
exec >>/root/uci-defaults.log 2>&1

echo "Setting DHCP settings."

uci -q batch << EOI

set dhcp.@dnsmasq[0]=dnsmasq
set dhcp.@dnsmasq[0].domainneeded='1'
set dhcp.@dnsmasq[0].localise_queries='1'
set dhcp.@dnsmasq[0].rebind_protection='1'
set dhcp.@dnsmasq[0].rebind_localhost='1'
set dhcp.@dnsmasq[0].local='/lan/'
set dhcp.@dnsmasq[0].expandhosts='1'
set dhcp.@dnsmasq[0].authoritative='1'
set dhcp.@dnsmasq[0].readethers='1'
set dhcp.@dnsmasq[0].leasefile='/tmp/dhcp.leases'
set dhcp.@dnsmasq[0].localservice='1'
set dhcp.@dnsmasq[0].domain='home.arpa'
set dhcp.@dnsmasq[0].resolvfile='/tmp/resolv.conf.d/resolv.conf.auto'
set dhcp.lan=dhcp
set dhcp.lan.interface='lan'
set dhcp.lan.start='100'
set dhcp.lan.limit='150'
set dhcp.lan.leasetime='12h'
set dhcp.lan.dhcpv6='server'
set dhcp.lan.ra='server'
set dhcp.lan.ra_management='1'
set dhcp.lan.netmask='255.255.255.0'
set dhcp.lan.dhcp_option='6,1.1.1.1,1.0.0.1,8.8.8.8,10.0.0.1'
set dhcp.wan=dhcp
set dhcp.wan.interface='wan'
set dhcp.wan.ignore='1'
set dhcp.odhcpd=odhcpd
set dhcp.odhcpd.maindhcp='0'
set dhcp.odhcpd.leasefile='/tmp/hosts/odhcpd'
set dhcp.odhcpd.leasetrigger='/usr/sbin/odhcpd-update'
set dhcp.odhcpd.loglevel='4'
add dhcp host
set dhcp.@host[-1].mac='00:80:92:8D:B6:0E'
set dhcp.@host[-1].name='brother928DB60E'
set dhcp.@host[-1].dns='1'
set dhcp.@host[-1].ip='10.0.0.173'
add dhcp host
set dhcp.@host[-1].name='Opslag'
set dhcp.@host[-1].ip='10.0.0.90'
set dhcp.@host[-1].mac='90:09:D0:79:10:73'
add dhcp host
set dhcp.@host[-1].mac='00:1E:06:42:DC:C7'
set dhcp.@host[-1].dns='1'
set dhcp.@host[-1].ip='10.0.0.98'
set dhcp.@host[-1].name='homeassistant'
add dhcp host
set dhcp.@host[-1].name='SynologyNAS'
set dhcp.@host[-1].ip='10.0.0.91'
set dhcp.@host[-1].mac='90:09:D0:79:10:74'
add dhcp host
set dhcp.@host[-1].name='PlayFi-Play-Fi-Device--2C6B95-'
set dhcp.@host[-1].ip='10.0.0.220'
set dhcp.@host[-1].mac='62:B6:06:2C:6B:95'

commit dhcp
EOI


echo '-- config after:'
uci show dhcp
echo
