#!/bin/sh -e
exec >>/root/uci-defaults.log 2>&1
# Setup tailscale

echo "================="
echo "Setting up tailscale"
uci -q batch << EOI

set network.Tailscale=interface
set network.Tailscale.proto='unmanaged'
set network.Tailscale.device='tailscale0'

add firewall zone
set firewall.@zone[-1].name='tailscale'
set firewall.@zone[-1].network='Tailscale'
set firewall.@zone[-1].input='ACCEPT'
set firewall.@zone[-1].output='ACCEPT'
set firewall.@zone[-1].forward='ACCEPT'
set firewall.@zone[-1].masq='1'
set firewall.@zone[-1].mtu_fix='1'

add firewall forwarding
set firewall.@forwarding[-1].name='tailscale2lan'
set firewall.@forwarding[-1].src='tailscale'
set firewall.@forwarding[-1].dest='lan'
add firewall forwarding
set firewall.@forwarding[-1].name='tailscale2wan'
set firewall.@forwarding[-1].src='tailscale'
set firewall.@forwarding[-1].dest='wan'
add firewall forwarding
set firewall.@forwarding[-1].name='lan2tailscale'
set firewall.@forwarding[-1].src='lan'
set firewall.@forwarding[-1].dest='tailscale'

commit network
commit firewall

EOI

echo "Execute 'tailscale up' once to authenticate"
echo "If this errors, you might need to manually up the machine once, or update the embedded auth-key which expires after only 90 days"

tailscale up --auth-key=tskey-auth-ktuE1QUo8821CNTRL-SUNRJmL8AiCysoZABHZciC5Wm3ZXWVYX

echo '-- config after:'
uci show tailscale
uci show firewall
echo

